name: Sequential Execution Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run Tests Sequentially
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: Install dependencies
      run: npm install

    - name: Run Tests
      run: npm run test

    - name: Upload Test Results
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: ./test-results
