name: Sequential Execution Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run Tests Sequentially
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 16.x

    - name: Install dependencies
      run: npm install

    - name: Run Tests
      run: npm run test

    - name: Upload Test Results
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ./test-results

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
      
        SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: 'Test Automation Report https://github.com/DattaFugare/Framework/actions/runs/${{github.run_id}}'
        SLACK_TITLE: Cypress web test
        SLACK_USERNAME: rtCamp
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}